// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Nest.Watcher")]
[assembly: AssemblyCopyrightAttribute("Elasticsearch 2015")]
[assembly: AssemblyDescriptionAttribute("Watcher is a plugin for Elasticsearch that provides alerting and notification based on changes in your data. This nuget extends NEST allowing you to interface with the watcher plugin")]
[assembly: AssemblyCompanyAttribute("Elasticsearch")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0-beta1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
