// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Nest.Watcher.Tests.Integration")]
[assembly: AssemblyCopyrightAttribute("Elasticsearch 2015")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("Elasticsearch")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0-beta1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
